demo_app/urls.py
from django.urls import path
from . import views

app_name = 'demo_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.blogs, name='blogs'),
    path('blog/<int:id>/', views.blog, name='blog'),
    path('blog/edit/<int:id>/', views.edit, name='edit'),
    path('blog/new/', views.new, name='new'),
    path('register/', views.registration, name='register'),
    path('blog/<int:id>/delete/', views.delete, name='delete'),
    path('blog/newRating/<int:id>/', views.newRating, name='newRating'),
    path('blog/ratings/<int:id>/', views.ratings, name='ratings')
]

vezbe11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('demo_app.urls'))
]

demo_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

class Rating(models.Model):
    value = models.IntegerField(default = 1, validators = [MinValueValidator(1), MaxValueValidator(10)])
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE)

    def __str__(self):
        return self.content

demo_app/forms.py
from django.forms import ModelForm, Form
import django.forms as f
from .models import Blog, User, Rating


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'category', 'content']
        
class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['value']


class RegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

demo_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .models import Blog, User, Rating
from .forms import BlogForm, RegistrationForm, RatingForm


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Vezbe 13'})
    else:
        return redirect('demo_app:blogs')


@login_required
def blogs(req):
    tmp = Blog.objects.all()
    return render(req, 'blogs.html', {'blogs': tmp})


@login_required
def blog(req, id):
    tmp = get_object_or_404(Blog, id=id)
    return render(req, 'blog.html', {'blog': tmp, 'page_title': tmp.title})


@permission_required('demo_app.change_blog')
def edit(req, id):
    if req.method == 'POST':
        form = BlogForm(req.POST)

        if form.is_valid():
            a = Blog.objects.get(id=id)
            a.title = form.cleaned_data['title']
            a.category = form.cleaned_data['category']
            a.content = form.cleaned_data['content']
            a.save()
            return redirect('demo_app:blogs')
        else:
            return render(req, 'edit.html', {'form': form, 'id': id})
    else:
        a = Blog.objects.get(id=id)
        form = BlogForm(instance=a)
        return render(req, 'edit.html', {'form': form, 'id': id})

@permission_required('blogs.delete_blog')
def delete(request, id):
    temp = Blog.objects.get(pk=id)
    temp.delete()
    return redirect('demo_app:blogs')

@permission_required('demo_app.add_blog')
def new(req):
    if req.method == 'POST':
        form = BlogForm(req.POST)

        if form.is_valid():
            a = Blog(title=form.cleaned_data['title'], category=form.cleaned_data['category'], content=form.cleaned_data['content'], owner=req.user)
            a.save()
            return redirect('demo_app:blogs')
        else:
            return render(req, 'new.html', {'form': form})
    else:
        form = BlogForm()
        return render(req, 'new.html', {'form': form})

@login_required
def newRating(req, id):
    if req.method == 'POST':
        form = RatingForm(req.POST)

        if form.is_valid():
            a = Blog.objects.get(id=id)
            c = Rating(value=form.cleaned_data['value'], blog=a)
            c.save()
            return redirect('demo_app:blogs')
        else:
            return redirect('demo_app:blogs')
    else:
        c = Rating(value="")
        form = RatingForm(instance=c)
        return render(req, 'newRating.html', {'form': form, 'id': id})

@login_required
def ratings(req, id):
    tmp = Rating.objects.filter(blog_id=id)
    return render(req, 'ratings.html', {'ratings': tmp})


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username=username, password=password)
            user.save()
            return redirect('demo_app:index')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

demo_app/templates/blog.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ blog.title }}
                {% if perms.demo_app.change_blog %}
                    <a href="{% url 'demo_app:edit' blog.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                    <a href="{% url 'demo_app:delete' blog.id %}">
                        <span class="badge badge-primary">delete</span>
                    </a>
            
                {% endif %}
                <a href="{% url 'demo_app:newRating' blog.id %}">
                    <span >Add rating</span>
                </a>
                <a href="{% url 'demo_app:ratings' blog.id %}">
                  <span >All ratings</span>
                </a>
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>Kategorija: {{ blog.category }}</p>
                <p>{{ blog.content }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{ blog.owner.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>

{% endblock %}

demo_app/templates/blogs.html
{%  extends 'master.html' %}

{% block title %}
    Blogs
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for blog in blogs %}
            <a class="list-group-item list-group-item-action" href="{% url 'demo_app:blog' blog.id %}">
                {{ blog.title }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

demo_app/templates/delete.html
{% extends 'master.html' %} {% block title %} Delete animal {% endblock %} {%
    block content %}
    
<button class = "primary">Delete</button>

{% endblock %}

demo_app/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.name }}" value="{{ form.title.value }}">
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">{{ form.category.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.category.id_for_label }}" name="{{ form.category.name }}" value="{{ form.category.value }}">
            {% if form.category.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.category.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5">{{ form.content.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

demo_app/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
    <a href="{% url 'demo_app:register'%}">Click here to sign up.</a>
{% endblock %}

demo_app/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label_tag }}</label>
            <p>{{ form.title }}</p>
            {% if form.title.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.title.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">{{ form.category.label_tag }}</label>
            <p>{{ form.category }}</p>
            {% if form.category.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.category.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <p>{{ form.content }}</p>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

demo_app/templates/newRating.html
{% extends 'master.html' %}

{% block title %}
    New comment
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:newRating' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.value.id_for_label }}">{{ form.value.label_tag }}</label>
            <p></p>
            {{form.value}}
        </div>

        <input type="submit" class="btn btn-secondary" value="Add"/>
    </form>

{% endblock %}

demo_app/templates/ratings.html
{%  extends 'master.html' %}

{% block title %}
    Ratings
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for rating in ratings %}
            <a class="list-group-item list-group-item-action">
                {{ rating.value }}
            </a>
        {% endfor %}
    </div>

{% endblock %}

demo_app/templates/register.html
{% extends 'master.html' %} {% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'demo_app:blogs' %}">
        <img
            src="{% static 'img/bloglogo.png' %}"
            width="30"
            height="30"
            class="d-inline-block align-top"
            alt="logo"
        />
        Vezbe 13
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.demo_app.add_blog %}
            <a class="nav-link disabled" href="{% url 'demo_app:new' %}"
                >New blog</a
            >
            {% else %}
            <a class="nav-link" href="{% url 'demo_app:new' %}">New blog</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'logout' %}"
        >Logout {{ user.get_username }}</a
    >
    {% endif %}
</nav>

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <title>
            {% block title %} {{ page_title|default:"Blogovi" }} {% endblock title %}
        </title>

        <link
            rel="shortcut icon"
            type="image/png"
            href="{% static 'favicon.ico' %}"
        />

        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/bootstrap.min.css' %}"
        />

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
    </head>

    <body>
        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
            <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>
    </body>
</html>